#!/bin/bash
PLATFORM="arm-linux-gnueabihf"
declare -a paths=("/usr/lib/$PLATFORM" "/lib/$PLATFORM")

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <user>@<raspberry-ip>"
    exit 1
fi

for d in "${paths[@]}"; do
    echo "Mounting $d..."
    sudo mkdir $d
    sudo chmod 755 $d
    sudo sshfs $1:$d $d -o allow_other
done

echo "Compiling..."
cargo build --target=arm-unknown-linux-gnueabihf

for d in "${paths[@]}"; do
    echo "Unmounting $d..."
    sudo fusermount -u $d
    sudo rmdir $d
done

echo "All done."

