#!/bin/bash

set -x -e

PLATFORM="arm-linux-gnueabihf"
SSH_PORT=22
declare -a paths=("/usr/lib/$PLATFORM" "/lib/$PLATFORM")

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
    echo "Usage: $0 <user>@<raspberry-ip> [port]"
    exit 1
fi

if [ $# -eq 2 ]
then
  echo "Using port $2 for ssh"
  SSH_PORT="$2"
fi

for d in "${paths[@]}"
do
    echo "Cleaning up"
    sudo fusermount -u $d > /dev/null 2>&1 || true
    sudo rmdir $d > /dev/null 2>&1 || true
done

for d in "${paths[@]}"; do
  if ! [ -d $d ]; then
    echo "Mounting $d..."
    sudo mkdir $d
    sudo chmod 755 $d
    sudo sshfs -p $SSH_PORT $1:$d $d -o allow_other
  else
    echo "$d already exists"
  fi
done

echo "Compiling..."
cargo build --release --target=arm-unknown-linux-gnueabihf || true

for d in "${paths[@]}"
do
    echo "Unmounting $d..."
    sudo fusermount -u $d
    sudo rmdir $d
done

echo "All done."
